language: go
go:
- 1.6
- 1.9
env: PATH=/home/travis/gopath/bin:$PATH
script:
  - make test
after_script:
  - make cover
notifications:
  slack:
    secure: cPeJRg+ouTlemEV5UM4muhDwtIM0dktcs3mnfB73oZ2MGOimv/DFpL+VTRLlkWau8l0dT4ngLlGPcveLrXQXwps2LsJMr+gS6Az/CAQCIl21oj4bnjs5uGYTG8hM8ymVzGINPNnj5Fnn5DUMunA2sow30qxfuCnSUMGot2nFRKw=
